name: Deploy fontend application
on:
  push:
    branches:
        -main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:  
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        useu: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/setup-buildx-action@v2
        with:
          usename: ${{ secrets.DOCKER_HUB_USENAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: prepare the docker-compose run
        run: |
              ls -l
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
        context: .
        push: true
        tags: deityzs/234-deploylab-fontend:latest
      -
       name: prepare the docker-compose run
       run: |
              mkdir 234-deploylab-fontend
              cp docker-compose.yml 234-deploy-fontend/docker-compose.yml
              cd 234 deploylab-fontend
              docker-compose -H ${{ secrets.HOSE_SERVER }} down
              docker-compose -H ${{ secrets.HOSE_SERVER }} pull
              docker-compose -H ${{ secrets.HOSE_SERVER }} up -d
      
      version: '3.3'
      services:
        fontend:
          image: deityzs/234-deploylab-fontend:latest
          ports:
            - "8086:80"